@settings(defaultLengthUnit = in)

slotDepth = 0.1
slotWidth = 0.21
millLength = 1
arborDiameter = .5
arborOffset = .625

// adjusted by hand to get to a slice of 45deg (360 deg / 8 teeth)
yRel008 = -0.003919794
xRel008 = 0.02668365
len001 = 0.063
yRel007 = -0.014
xRel007 = 0.088
yRel006 = -0.058
xRel006 = 0.048
yRel005 = -0.1
xRel005 = -0.041
yRel004 = -0.038
xRel004 = 0.055
yRel003 = -0.006
xRel003 = 0.022
yRel002 = 0.069
xRel002 = 0.116
yRel001 = .537
xRel001 = 0.035
toothSketch = startSketchOn(XY)
toothAngleStart = 90deg - 3.73deg
toothLength = 0.54
profileStart = polar(angle = toothAngleStart, length = toothLength)
profileEnd = polar(angle = toothAngleStart - 45, length = toothLength)
toothProfile = startProfile(toothSketch, at = [0, 0])
  |> line(end = profileStart)
  |> line(end = [xRel002, yRel002])
  |> line(end = [xRel003, yRel003])
  |> line(end = [xRel004, yRel004])
  |> line(end = [xRel005, yRel005])
  |> tangentialArc(end = [xRel006, yRel006])
  |> tangentialArc(end = [xRel007, yRel007], tag = $seg01)
  |> angledLine(angle = tangentToEnd(seg01), length = len001)
  |> tangentialArc(end = [xRel008, yRel008])
  |> line(endAbsolute = profileEnd)
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)])
  |> close()
extrude001 = extrude(toothProfile, length = millLength)
pattern001 = patternCircular3d(
  extrude001,
  instances = 8,
  axis = Z,
  center = [0, 0, 0],
)
solid001 = union(pattern001)
